create PROCEDURE SP_CheckJobCard
(
	@JobCardNo int = 0
)
AS
BEGIN
SELECT j.JOB_CARD_NO as [JOB_CARD_NO],JEM.EQUIPTMENT_MATERIALS_ID as [EquipID] FROM job j
LEFT JOIN EMPLOYEE_JOB_CARD ej on ej.JOB_CARD_NO = j.JOB_CARD_NO
LEFT JOIN JOB_EQUIPTMENT_MATERIALS jem on jem.JOB_CARD_NO = j.JOB_CARD_NO
WHERE j.JOB_CARD_NO = 1017
END