CREATE PROCEDURE SP_InsertEmployee
(
	@EMPLOYEE_NO VARCHAR (6)  = '',
	@NAME VARCHAR (50) = '',
	@SURNAME VARCHAR (50)  = ''
)
AS
BEGIN
	INSERT INTO EMPLOYEE (EMPLOYEE_NO,[NAME],SURNAME)
	VALUES (@EMPLOYEE_NO,@NAME,@SURNAME)
END
