CREATE PROCEDURE SP_CreateJob
(
	@JOB_CARD_NO INT   = 0,
	@NO_OF_DAYS INT = 0,
	@CUSTOMER_ID INT = 0
)
AS
BEGIN
	INSERT INTO JOB(JOB_CARD_NO,NO_OF_DAYS)
	VALUES (@JOB_CARD_NO,@NO_OF_DAYS)
	INSERT INTO QUOTATION(JOB_CARD_NO,CUSTOMER_ID)
	VALUES (@JOB_CARD_NO,@CUSTOMER_ID)
END