CREATE PROCEDURE SP_InsertCustomer
(
	@NAME VARCHAR (50) = '',
	@SURNAME VARCHAR (50)  = '',
	@ADDRESS_LINE_ONE VARCHAR (250) = '',
	@ADDRESS_LINE_TWO VARCHAR (250) = '',
	@CITY VARCHAR (100) = '',
	@POSTAL_CODE VARCHAR (5) = ''
)
AS
BEGIN
	INSERT INTO CUSTOMER([NAME],SURNAME,ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,CITY,POSTAL_CODE)
	VALUES (@NAME,@SURNAME,@ADDRESS_LINE_ONE,@ADDRESS_LINE_TWO,@CITY,@POSTAL_CODE)
END
