CREATE PROCEDURE SP_SelectMaterials
(
	@EQUIPTMENT_MATERIALS_ID INT = 0,
	@POWER_POINTS INT = 0,
	@STANDARD_ELECTRICAL_WIRING INT = 0
)
AS
BEGIN
	INSERT INTO MATERIALS(EQUIPTMENT_MATERIALS_ID,POWER_POINTS,STANDARD_ELECTRICAL_WIRING)
	VALUES(@EQUIPTMENT_MATERIALS_ID,@POWER_POINTS,@STANDARD_ELECTRICAL_WIRING)

END