CREATE PROCEDURE SP_UpdateCustomer
(
	@CUSTOMER_ID INT = 0,
	@NAME VARCHAR (50) = '',
	@SURNAME VARCHAR (50)  = '',
	@ADDRESS_LINE_ONE VARCHAR (250) = '',
	@ADDRESS_LINE_TWO VARCHAR (250) = '',
	@CITY VARCHAR (100) = '',
	@POSTAL_CODE VARCHAR (5) = ''
)
AS
BEGIN
	UPDATE CUSTOMER
	SET [NAME] = @NAME,
		SURNAME = @SURNAME,
		ADDRESS_LINE_ONE = @ADDRESS_LINE_ONE,
		ADDRESS_LINE_TWO = @ADDRESS_LINE_TWO,
		CITY = @CITY,
		POSTAL_CODE = @POSTAL_CODE
	WHERE CUSTOMER_ID = @CUSTOMER_ID
END
